### ISSUE TITLE
[DSM] Thu Jun 30 2022

### ISSUE THREAD

**Issue by atls-github** [atls-academy/dsm#468]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by Gradesor** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-academy/Gradesor.github.io/issues/3
- - создал базу, форма логина готова на 80%
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-academy/Gradesor.github.io/issues/3
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
- работа, на связи с 16:00 мск
