### ISSUE TITLE
[DSM] Sat Mar 18 2023

### ISSUE THREAD

**Issue by atls-github** [atls-academy/dsm#663]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by oksssvv** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-academy/oksssvv.github.io/issues/3 (разработала механизм авторизации)

#### Какие задачи будешь делать сегодня? Укажи #issues
-https://github.com/atls-academy/oksssvv.github.io/issues/3 (Вношу правки, довожу до ума)
